### PR TITLE
feat: `header`, disable setting `X-Robots-Tag` header

### LINKED ISSUE #133: Add an option to disable setting `X-Robots-Tag` header of routeRules
Hi!

I'm deploying my site using the Cloudflare Pages Free Plan, which allows a maximum of 100 header rules in the `_headers` file.

Setting `X-Robots-Tag` to all routeRules will make `_headers` file exceed the limit and will ignore other necessary headers.

It will be better to have an option to disable setting headers like `metaTag` does for meta tag.

### PR DESCRIPTION
**Pull request by HADB**
### 🔗 Linked issue

resolves #133 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add an option to disable setting `X-Robots-Tag` header.

### CODE REVIEW

**Comment by harlan-zw** [comment]
Thanks, I think there may be some runtime logic that also applies these headers. Do you think we should be covering that with this flag or should we have two separate flags?

Btw I think we we could disable this feature by default for cloudflare but I'll set up that up outside this PR.

**Comment by HADB** [comment]
Hi, I pushed a new commit which covers runtime header logic.

**Comment by harlan-zw** [comment]
Great work, thank you for the help. I'll aim to get this merged and released tomorrow.

If you have any time in the meantime to add a test it would be really appreicated.

**Review by harlan-zw — APPROVED** [review]

**Comment by HADB** [comment]
I added a test for server response header. I have no idea how to test the generated `_header` file. But it works as expected when I run `generate` script manually.

**Pull request merged**
